"""Quitar datos innecesarios

Revision ID: 89f45ecbbacd
Revises: a28158ea515f
Create Date: 2026-03-17 00:28:40.494561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f45ecbbacd'
down_revision = 'a28158ea515f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pizzas', ['id_pizza'], ['id_pizza'])
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'])
        batch_op.drop_column('nombre')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clientes', ['id_cliente'], ['id_cliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
