"""Cambiar tipo de dato fecha

Revision ID: a28158ea515f
Revises: 
Create Date: 2026-03-16 22:14:52.655237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a28158ea515f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'])
        batch_op.create_foreign_key(None, 'pizzas', ['id_pizza'], ['id_pizza'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'clientes', ['id_cliente'], ['id_cliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
